# Generated by Django 3.1.3 on 2020-11-29 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('brand', models.CharField(max_length=100)),
                ('main_image', models.ImageField(default='', upload_to='main_image/%Y%m%d')),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('out_of_stock', models.BooleanField(default=False)),
                ('size', models.CharField(max_length=200)),
                ('is_new_arrival', models.BooleanField(default=False)),
                ('image1', models.ImageField(blank=True, upload_to='image1/%Y%m%d')),
                ('image2', models.ImageField(blank=True, upload_to='image2/%Y%m%d')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shops.shop')),
            ],
        ),
    ]
