# Generated by Django 3.1.3 on 2020-12-02 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        ('products', '0004_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='shop',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shops.shop'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='adv_image',
            field=models.ImageField(default='', upload_to='adv_image/%Y%m%d'),
        ),
    ]
