# Generated by Django 3.1.3 on 2020-12-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_advertisement_advertisement_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='adv_image',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='adv_image1',
            field=models.ImageField(default='', upload_to='adv_image1/%Y%m%d'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='adv_image2',
            field=models.ImageField(default='', upload_to='adv_image2/%Y%m%d'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='adv_image3',
            field=models.ImageField(default='', upload_to='adv_image3/%Y%m%d'),
        ),
    ]
