# Generated by Django 3.1.3 on 2020-12-13 06:19

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201202_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(default='', max_length=254)),
                ('address', models.CharField(max_length=250)),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='adv_image2',
            field=models.ImageField(blank=True, default='', upload_to='adv_image2/%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='adv_image3',
            field=models.ImageField(blank=True, default='', upload_to='adv_image3/%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
